export const StoreDefided = {
    POST_DEFINED: {
        ADD_POST: 'ADD_POST',
        FETCH_POSTS: 'FETCH_POSTS',
        DEL_POST: 'DEL_POST',
        DETAIL_POST_WITH_EDIT: 'DETAIL_POST_WITH_EDIT'
    },
    TAG_DEFINED: {
        ADD_TAG: 'ADD_TAG',
        FETCH_TAGS:'FETCH_TAGS',
        UPDATE_TAG:'UPDATE_TAG',
        DEL_TAG:'DEL_TAG',
        DETAIL_TAG_WITH_EDIT:'DETAIL_TAG_WITH_EDIT',
        DETAIL_TAG:'DETAIL_TAG',
    },
    SEO_DEFINED: {
        ADD_SEO: 'ADD_SEO',
        UPDATE_SEO: 'UPDATE_SEO',
        FETCH_SEOS: 'FETCH_SEOS',
        DETAIL_SEO: 'DETAIL_SEO'
    },
    SETTING_DEFINED: {
        ADD_SETTING: 'ADD_SETTING',
        UPDATE_SETTING: 'UPDATE_SETTING',
        FETCH_SETTINGS: 'FETCH_SETTINGS',
        DETAIL_SETTING: 'DETAIL_SETTING'
    }
}