export const StoreDefided = {
    POST_DEFINED: {
        ADD_ITEM: 'ADD_ITEM',
        FETCH_ITEMS: 'FETCH_ITEMS',
        DEL_ITEM: 'DEL_ITEM',
        DETAIL_POST_WITH_EDIT: 'DETAIL_POST_WITH_EDIT'
    },
    TAG_DEFINED: {
        ADD_TAG: 'ADD_TAG',
        FETCH_TAGS:'FETCH_TAGS',
        UPDATE_TAG:'UPDATE_TAG',
        DEL_TAG:'DEL_TAG',
        DETAIL_TAG_WITH_EDIT:'DETAIL_TAG_WITH_EDIT',
        DETAIL_TAG:'DETAIL_TAG',
    },
    SEO_DEFINED: {
        ADD_ITEM: 'ADD_ITEM',
        UPDATE_ITEM: 'UPDATE_ITEM',
        FETCH_ITEMS: 'FETCH_ITEMS',
        DETAIL_SEO: 'DETAIL_SEO'
    },
    SETTING_DEFINED: {
        ADD_ITEM: 'ADD_ITEM',
        UPDATE_ITEM: 'UPDATE_ITEM',
        FETCH_ITEMS: 'FETCH_ITEMS',
        DETAIL_SETTING: 'DETAIL_SETTING'
    }
}